export const PROGRAM_OPTIONS = [
  {
    code: 'APE',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Applied Physics and Electronics',
    credits: '130 Credits',
  },
  {
    code: 'ANT',
    level: 'Undergraduate',
    title: 'Bachelor of Social Sciences in Anthropology',
    credits: '120 Credits',
  },
  {
    code: 'ARC',
    level: 'Undergraduate',
    title: 'Bachelor of Architecture',
    credits: '207 Credits',
  },
  {
    code: 'BIO',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Biotechnology',
    credits: '136 Credits',
  },
  {
    code: 'PHR',
    level: 'Undergraduate',
    title: 'Bachelor of Pharmacy (Hons.)',
    credits: '164 Credits',
  },
  {
    code: 'BBA',
    level: 'Undergraduate',
    title: 'Bachelor of Business Administration',
    credits: '130 Credits',
  },
  {
    code: 'ECO',
    level: 'Undergraduate',
    title: 'Bachelor of Social Science in Economics',
    credits: '120 Credits',
  },
  {
    code: 'MIC',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Microbiology',
    credits: '136 Credits',
  },
  {
    code: 'MAT',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Mathematics',
    credits: '127 Credits',
  },
  {
    code: 'LLB',
    level: 'Undergraduate',
    title: 'Bachelor of Laws (LL.B. Hons.)',
    credits: '135 Credits',
  },
  {
    code: 'CSE',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Computer Science & Engineering',
    credits: '136 Credits',
  },
  {
    code: 'CS',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Computer Science',
    credits: '124 Credits',
  },
  {
    code: 'ECE',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Electronic and Communication Engineering',
    credits: '136 Credits',
  },
  {
    code: 'GENED',
    level: 'Undergraduate',
    title: 'General Education',
    credits: '39 Credits',
  },
  {
    code: 'HIST_MINOR',
    level: 'Undergraduate',
    title: 'Minor in History',
    credits: '24 Credits',
  },
  {
    code: 'BA_EN',
    level: 'Undergraduate',
    title: 'Bachelor of Arts in English',
    credits: '132 Credits',
  },
  {
    code: 'PHY',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Physics',
    credits: '120 Credits',
  },
  {
    code: 'EEE',
    level: 'Undergraduate',
    title: 'Bachelor of Science in Electrical and Electronic Engineering',
    credits: '136 Credits',
  },
  {
    code: 'AELS',
    level: 'Undergraduate',
    title: 'Bachelor of Arts in Applied English Language Studies',
    credits: 'Credits Not Specified',
  },
  {
    code: 'BDM',
    level: 'Undergraduate',
    title: 'Bachelor of Disaster Management in Humanitarian Response',
    credits: '141 Credits',
  },
];
